---
- name: debug stuff
  hosts: testbox1
  become: true
  roles:
    - redhat.rhel_system_roles.kernel_settings
  vars:
    kernel_settings_sysctl:
      - name: fs.file-max
        value: 400000
      - name: kernel.threads-max
        value: 65536

  tasks:
    - name: Extend the logical volume to consume all remaining space
      community.general.lvol:
        vg: rootvg
        lv: rootlv
        size: +100%FREE
