

---
- name: debug stuff
  hosts: all
  become: true
  tasks:
  
  - name: run setup
    setup:
    
  - name: debug username
    debug:
      var: ansible_user      
  - name: debug ssh password
    debug:
      var: ansible_ssh_password
